# Generated by Django 2.1.5 on 2019-02-02 15:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namek', models.CharField(max_length=200)),
                ('can_rockk', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='can_rock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='instrument',
            field=models.CharField(choices=[('g', 'Guitar'), ('b', 'Bass'), ('d', 'Drums')], default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='nam',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name="Member's name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='namee',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
